version: '3'

services:

  ###> doctrine/doctrine-bundle ###
  ### Docker-compose PostgreSQL сервер ###

  database:
    image: postgres:${POSTGRES_VERSION:-14.8}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pgs_arm_student}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bGGLgYqQJLDckv5H}
      POSTGRES_USER: ${POSTGRES_USER:-stasone}
    ports:
      - target: 5432
        published: 15432
        protocol: tcp
        mode: host
    volumes:
      - /var/www/arm/.docker/postgresql/data:/var/lib/postgresql/data
    labels:
      com.symfony.server.service-prefix: 'DATABASE_URL'
    networks:
      - nginx-php-PSQL

  ###< doctrine/doctrine-bundle ###

  php82-service:
    build:
      context: .
      dockerfile: /var/www/arm/.docker/php/Dockerfile
    container_name: php82-container
    ports:
      - "9000:9000"
    volumes:
      - /var/www/arm/app/arm-student-app:/var/www/project
      - /var/www/arm/.docker/certs:/var/www/ssl-home/project
      - /var/www/arm/.docker/supervisor:/etc/supervisor
      - /var/www/arm/.docker/logs/supervisor:/var/log/supervisor/
    networks:
      - nginx-php-PSQL

  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/arm/app/arm-student-app:/var/www/project
      - /var/www/arm/.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/www/arm/.docker/logs/nginx:/var/log/nginx/
      - /var/www/arm/.docker/certs:/var/www/ssl-home/project
    depends_on:
      - php82-service
    networks:
      - NPMproxy
      - nginx-php-PSQL




  ###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    restart: unless-stopped
    environment:
      SERVER_NAME: ':3000'
      MERCURE_PUBLISHER_JWT_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.7Hlt-ke43l49emcnOvsmMa2VUCKhJoZEj8j1zTP4PfM'
      MERCURE_SUBSCRIBER_JWT_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.7Hlt-ke43l49emcnOvsmMa2VUCKhJoZEj8j1zTP4PfM'
      CERT_FILE: '/var/www/ssl-home/project/cert.crt'
      DEBUG: 1
      KEY_FILE: '/var/www/ssl-home/project/key.key'
      MERCURE_EXTRA_DIRECTIVES: |
        auto_https off
    ports:
      - "3000:3000"
    volumes:
      - /var/www/arm/.docker/certs:/var/www/ssl-home/project
      - mercure_data:/data
      - mercure_config:/config
###< symfony/mercure-bundle ###

volumes:
  ###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
  ###< symfony/mercure-bundle ###
  ###> doctrine/doctrine-bundle ###

  # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
  # - /var/www/arm/docker/db/data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

networks:
  nginx-php-PSQL:
  NPMproxy: