version: '3'

services:

  ###> doctrine/doctrine-bundle ###
  ### Docker-compose PostgreSQL сервер ###
  #database:
  #  image: postgres:${POSTGRES_VERSION:-14}-alpine
  #  environment:
  #    POSTGRES_DB: ${POSTGRES_DB:-pgs_arm_student}
  # You should definitely change the password in production
  #    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bGGLgYqQJLDckv5H}
  #    POSTGRES_USER: ${POSTGRES_USER:-stasone}
  #  ports:
  #    - target: 5432
  #      published: 15432
  #      protocol: tcp
  #      mode: host
  #  volumes:
  #    - ./.docker/postgresql/data:/var/lib/postgresql/data
  #  labels:
  #    com.symfony.server.service-prefix: 'DATABASE'
  ###< doctrine/doctrine-bundle ###

  php82-service:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: php82-container
    ports:
      - "9000:9000"
    volumes:
      - ./app/arm-student-app:/var/www/project
    networks:
      - nginx-php-PSQL

  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./app/arm-student-app:/var/www/project
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php82-service
    networks:
      - nginx-php-PSQL




  ###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    restart: unless-stopped
    environment:
      SERVER_NAME: ':3000'
      MERCURE_PUBLISHER_JWT_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.7Hlt-ke43l49emcnOvsmMa2VUCKhJoZEj8j1zTP4PfM'
      MERCURE_SUBSCRIBER_JWT_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.7Hlt-ke43l49emcnOvsmMa2VUCKhJoZEj8j1zTP4PfM'
      MERCURE_EXTRA_DIRECTIVES: |
        auto_https off
    ports:
      - "3000:3000"
      - "444:443"
      - "2019:2019"

    volumes:
      - mercure_data:/data
      - mercure_config:/config
###< symfony/mercure-bundle ###

volumes:
  ###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
  ###< symfony/mercure-bundle ###
  ###> doctrine/doctrine-bundle ###

  # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
  # - ./docker/db/data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

networks:
  nginx-php-PSQL: